apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}       # 80
      targetPort: {{ .Values.service.targetPort }} # 8085
      protocol: TCP
  selector:
    app: {{ include "my-helm-chart.fullname" . }}